Traceback (most recent call last):
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pozidriv = mpimg.imread('0_Schraubenkopfbilder_28x28/pozidriv/pozidriv 28x28_gray.jpg')
philips = mpimg.imread('0_Schraubenkopfbilder_28x28/philips/philips 28x28_gray.jpg')
innensechskant = mpimg.imread('0_Schraubenkopfbilder_28x28/innensechskant/innensechskant 28x28_gray.png')
sechskant = mpimg.imread('0_Schraubenkopfbilder_28x28/sechskant/sechskant 28x28_gray.jpg')
torx = mpimg.imread('0_Schraubenkopfbilder_28x28/torx/torx 28x28_gray.jpg')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_14088/271119621.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mpozidriv[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'0_Schraubenkopfbilder_28x28/pozidriv/pozidriv 28x28_gray.jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mphilips[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'0_Schraubenkopfbilder_28x28/philips/philips 28x28_gray.jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0minnensechskant[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'0_Schraubenkopfbilder_28x28/innensechskant/innensechskant 28x28_gray.png'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0msechskant[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'0_Schraubenkopfbilder_28x28/sechskant/sechskant 28x28_gray.jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mtorx[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'0_Schraubenkopfbilder_28x28/torx/torx 28x28_gray.jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\py37\lib\site-packages\matplotlib\image.py[0m in [0;36mimread[1;34m(fname, format)[0m
[0;32m   1558[0m                     [0mresponse[0m [1;33m=[0m [0mio[0m[1;33m.[0m[0mBytesIO[0m[1;33m([0m[0mresponse[0m[1;33m.[0m[0mread[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1559[0m                 [1;32mreturn[0m [0mimread[0m[1;33m([0m[0mresponse[0m[1;33m,[0m [0mformat[0m[1;33m=[0m[0mext[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1560[1;33m     [1;32mwith[0m [0mimg_open[0m[1;33m([0m[0mfname[0m[1;33m)[0m [1;32mas[0m [0mimage[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1561[0m         return (_pil_png_to_float_array(image)
[0;32m   1562[0m                 [1;32mif[0m [0misinstance[0m[1;33m([0m[0mimage[0m[1;33m,[0m [0mPIL[0m[1;33m.[0m[0mPngImagePlugin[0m[1;33m.[0m[0mPngImageFile[0m[1;33m)[0m [1;32melse[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\py37\lib\site-packages\PIL\ImageFile.py[0m in [0;36m__init__[1;34m(self, fp, filename)[0m
[0;32m    107[0m         [1;32mif[0m [0misPath[0m[1;33m([0m[0mfp[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    108[0m             [1;31m# filename[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 109[1;33m             [0mself[0m[1;33m.[0m[0mfp[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0mfp[0m[1;33m,[0m [1;34m"rb"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    110[0m             [0mself[0m[1;33m.[0m[0mfilename[0m [1;33m=[0m [0mfp[0m[1;33m[0m[1;33m[0m[0m
[0;32m    111[0m             [0mself[0m[1;33m.[0m[0m_exclusive_fp[0m [1;33m=[0m [1;32mTrue[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '0_Schraubenkopfbilder_28x28/innensechskant/innensechskant 28x28_gray.png'
FileNotFoundError: [Errno 2] No such file or directory: '0_Schraubenkopfbilder_28x28/innensechskant/innensechskant 28x28_gray.png'

