Traceback (most recent call last):
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# training_data anlegen
image_dataset = []

# Bildgr√∂√üe
IMG_SIZE=28

# Bilder und Kategorien in ein ... speichern:

def create_image_dataset():
    for category in CATEGORIES:  # jede Klasse

        path = os.path.join(DATADIR,category)  # create path to 
        class_num = CATEGORIES.index(category)  # get the classification ( 0= 1=

        for img in tqdm(os.listdir(path)):  # iterate over each image per Category
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                image_dataset.append([new_array, class_num])  # add this to our training_data
            except Exception as e:  # in the interest in keeping the output clean...
                pass
            except OSError as e:
                print("OSErrroBad img most likely", e, os.path.join(path,img))
            except Exception as e:
                print("general exception", e, os.path.join(path,img))

create_image_dataset()

print(len(image_dataset))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_18136/2467943809.py[0m in [0;36m<module>[1;34m[0m
[0;32m     25[0m                 [0mprint[0m[1;33m([0m[1;34m"general exception"[0m[1;33m,[0m [0me[0m[1;33m,[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0mpath[0m[1;33m,[0m[0mimg[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     26[0m [1;33m[0m[0m
[1;32m---> 27[1;33m [0mcreate_image_dataset[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     28[0m [1;33m[0m[0m
[0;32m     29[0m [0mprint[0m[1;33m([0m[0mlen[0m[1;33m([0m[0mimage_dataset[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_18136/2467943809.py[0m in [0;36mcreate_image_dataset[1;34m()[0m
[0;32m     10[0m     [1;32mfor[0m [0mcategory[0m [1;32min[0m [0mCATEGORIES[0m[1;33m:[0m  [1;31m# jede Klasse[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [1;33m[0m[0m
[1;32m---> 12[1;33m         [0mpath[0m [1;33m=[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0mDATADIR[0m[1;33m,[0m[0mcategory[0m[1;33m)[0m  [1;31m# create path to[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     13[0m         [0mclass_num[0m [1;33m=[0m [0mCATEGORIES[0m[1;33m.[0m[0mindex[0m[1;33m([0m[0mcategory[0m[1;33m)[0m  [1;31m# get the classification ( 0= 1=[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m [1;33m[0m[0m

[1;31mNameError[0m: name 'os' is not defined
NameError: name 'os' is not defined

